version: "3.6"
services:
    web:
        environment:
            - EXTENSION_KEY=phpmyadmin
            - PACKAGE_NAME=mehrwert/phpmyadmin

            - TYPO3_INSTALL_DB_DRIVER=mysqli
            - TYPO3_INSTALL_DB_USER=root
            - TYPO3_INSTALL_DB_PASSWORD=root
            - TYPO3_INSTALL_DB_HOST=db
            - TYPO3_INSTALL_DB_PORT=3306
            - TYPO3_INSTALL_DB_UNIX_SOCKET=
            - TYPO3_INSTALL_DB_USE_EXISTING=0
            - TYPO3_INSTALL_ADMIN_USER=admin
            - TYPO3_INSTALL_ADMIN_PASSWORD=password
            - TYPO3_INSTALL_SITE_NAME=EXT:phpmyadmin Dev Environment
            - TYPO3_INSTALL_SITE_SETUP_TYPE=site
            - TYPO3_INSTALL_WEB_SERVER_CONFIG=apache
        volumes:
            - type: bind
              source: ../
              target: /var/www/phpmyadmin
              consistency: cached
            - v11-data:/var/www/html/v11
            - v12-data:/var/www/html/v12
volumes:
    v11-data:
        name: "${DDEV_SITENAME}-v11-data"
    v12-data:
        name: "${DDEV_SITENAME}-v12-data"
